name: CICD
on:
  workflow_dispatch:
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "clone code from github"
  build:
     needs: code
     runs-on: ubuntu-latest
     steps:
       - name: build docker container
         run: echo "docker container build"
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: test the code
          run: echo "code tested sucessful hogya"
